name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Enable Corepack
        run: corepack enable

      - name: Prepare Yarn
        run: corepack prepare yarn@4.9.4 --activate

      - name: Install Backend Dependencies
        run: yarn install
        working-directory: backend

      - name: Build Backend
        run: yarn build
        working-directory: backend

      - name: Install Frontend Dependencies
        run: yarn install
        working-directory: frontend

      - name: Build Frontend
        run: yarn build
        working-directory: frontend
